" set leader key
let mapleader =" "

" Install Plugin manager (for neovim)
if ! filereadable(expand('~/.config/nvim/autoload/plug.vim'))
	echo "Downloading junegunn/vim-plug to manage plugins..."
	silent !mkdir -p ~/.config/nvim/autoload/
	silent !curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" > ~/.config/nvim/autoload/plug.vim
	autocmd VimEnter * PlugInstall
endif

" Plugins
call plug#begin('~/.config/nvim/plugged')
	
	Plug 'bling/vim-airline'
	Plug 'preservim/nerdtree'
	Plug 'tmsvg/pear-tree'
	Plug 'ycm-core/YouCompleteMe'
    Plug 'ap/vim-css-color'

call plug#end()

" Some basics
	nnoremap c "_c
	set nocompatible
	filetype plugin on
	set encoding=UTF-8	
	syntax on
	set tabstop=4 softtabstop=4
	set shiftwidth=4
	set expandtab
	set smartindent
	set viminfo+=n~/.config/vim/viminfo
	set encoding=utf-8
	set number relativenumber
	set bg=dark
	set go=a
	set mouse=a
	set nohlsearch
	set clipboard+=unnamedplus

" Scheme
colorscheme evening

if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endi

" Don't use your arrow keys, they are useless =))
noremap <Down> <Nop>
noremap <Up> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

noremap! <Down> <Nop>
noremap! <Up> <Nop>
noremap! <Left> <Nop>
noremap! <Right> <Nop>

" Move around split windows
	nmap <leader>h :wincmd h<CR>
    nmap <leader>j :wincmd j<CR>
    nmap <leader>k :wincmd k<CR>
    nmap <leader>l :wincmd l<CR>

" Move and format shortcut
	vmap J :m '>+1<CR>gv=gv
	vmap K :m '<-2<CR>gv=gv
	vmap <Tab> >gv
	vmap <S-Tab> <gv
    nmap <Tab> i<Tab><Esc>l

" NERDTree config
	map <leader>n :NERDTreeToggle<CR>
	let g:NERDTreeWinSize=20

" SFML compile shortcut
	map <leader>sf :w <bar> :! g++ -o sfml-app -lsfml-graphics -lsfml-window -lsfml-system 

" make shortcut
	map <leader>m :w <bar> :! sudo make clean install<CR>

" Enable autocompletion:
	set wildmode=longest,list,full

" Disables automatic commenting on newline:
	autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" YouCompleteMe
set completeopt-=preview
nmap <leader>gd :YcmCompleter GoTo<CR>
nmap <leader>gf :YcmCompleter FixIt<CR>
